---
title: Coffee Ratings
author: percentage-%
output: github_document
---

## Summary

As we all know, nowadays people are more and more getting used to having a cup of coffee in the morning to start the day. Therefore, an increasing amount of coffee lovers are trying to research the quality of coffees so that higher quality of coffee can be provided to the world. In order to find out how the quality of coffee can be related to other factors such as farms or companies, we are employing the database from TidyTuesday with the source James LeDoux & Coffee Quality Database. 


# Coffee Ratings
The data this week comes from James LeDoux & Coffee Quality Database (https://github.com/jldbc/coffee-quality-database). 
This Yorgos Askalidis - TWD (https://towardsdatascience.com/the-data-speak-ethiopia-has-the-best-coffee-91f88ed37e84) talks about Coffee Ratings in greater detail.
Credit: %(Percentage) 


```{r load-data, echo = FALSE}
# install.packages("tidytuesdayR"

tuesdata <- tidytuesdayR::tt_load('2020-07-07')
tuesdata <- tidytuesdayR::tt_load(2020, week = 28)

coffee_ratings <- tuesdata$coffee_ratings

coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')
```

## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data 

Askalidis, Y. (2019, March 26). The data is in: Ethiopia has the best coffee. Retrieved October 23, 2020, from https://towardsdatascience.com/the-data-speak-ethiopia-has-the-best-coffee-91f88ed37e84

LeDoux, J. (2018, June 17). Jldbc/coffee-quality-database. Retrieved October 23, 2020, from https://github.com/jldbc/coffee-quality-database

## References

James LeDoux & Coffee Quality Database (https://github.com/jldbc/coffee-quality-database). 
Yorgos Askalidis - TWD (https://towardsdatascience.com/the-data-speak-ethiopia-has-the-best-coffee-91f88ed37e84) 
